version: "3"
services:
    first-app:
        build: .
        volumes:
            - ./:/app
            - /app/node_modules
        ports:
            - "500:2500"
        environment: 
            - PORT=2500
